// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ZJJnj_QJEkN2Ftn9v3zpA9KduODKWVc',
    appId: '1:1075358443258:web:f03b8f42f6bb9739130b43',
    messagingSenderId: '1075358443258',
    projectId: 'scammie-63d2a',
    authDomain: 'scammie-63d2a.firebaseapp.com',
    databaseURL: 'https://scammie-63d2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scammie-63d2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGfYbcubUGM_09cb3Fpd1_ODOtSeI4HM',
    appId: '1:1075358443258:android:32a1a1b360520184130b43',
    messagingSenderId: '1075358443258',
    projectId: 'scammie-63d2a',
    databaseURL: 'https://scammie-63d2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scammie-63d2a.firebasestorage.app',
  );
  
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC-S7vcbph4zeL360B2HXtWw0zpCkB7Ak',
    appId: '1:1075358443258:ios:7c3e93747cd6493e130b43',
    messagingSenderId: '1075358443258',
    projectId: 'scammie-63d2a',
    databaseURL: 'https://scammie-63d2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scammie-63d2a.firebasestorage.app',
    iosBundleId: 'com.example.scammie',
  );
}
